apiVersion: v1
kind: Service
metadata:
  name : webserver-svc
  labels:
    app: frontend
  namespace: ola
spec: 
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
      app: frontend